//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkATTdesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.Matricula = new HashSet<Matricula>();
            this.Pasar_Lista = new HashSet<Pasar_Lista>();
        }
    
        public int id_alumno { get; set; }
        public Nullable<int> id_clase { get; set; }
        public string dni_alumno { get; set; }
        public string nombre_alumno { get; set; }
        public string apellido1_alumno { get; set; }
        public string apellido2_alumno { get; set; }
        public string email_alumno { get; set; }
        public string email_centro_alumno { get; set; }
        public int tel_alumno { get; set; }
        public System.DateTime nacimiento_alumno { get; set; }
        public System.DateTime incorp_alumno { get; set; }
        public string direccion_alumno { get; set; }
        public int horas_cursadas_totales_alumno { get; set; }
        public string año_cursando_alumno { get; set; }
    
        public virtual Clase Clase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula> Matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasar_Lista> Pasar_Lista { get; set; }
    }
}
