//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkATTdesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase_Modulo
    {
        public int id_clase_modulo { get; set; }
        public Nullable<int> id_clase1 { get; set; }
        public Nullable<int> id_modulo { get; set; }
    
        public virtual Clase Clase { get; set; }
        public virtual Modulo Modulo { get; set; }
    }
}
