//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkATTdesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Falta
    {
        public int id_falta { get; set; }
        public Nullable<int> id_pasar_lista { get; set; }
        public System.DateTime hora_falta { get; set; }
        public string motivo_falta { get; set; }
        public string documento_adj_falta { get; set; }
        public string comentario_falta { get; set; }
        public int estado_falta { get; set; }
    
        public virtual Pasar_Lista Pasar_Lista { get; set; }
    }
}
