//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkATTdesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int id_matricula { get; set; }
        public Nullable<int> id_modulo { get; set; }
        public Nullable<int> id_alumno { get; set; }
        public System.DateTime fecha_matricula { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Modulo Modulo { get; set; }
    }
}
