//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkATTdesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasar_listas_grupo
    {
        public int id_lista_grupo { get; set; }
        public System.DateTime hora_inicio { get; set; }
        public System.DateTime hora_final { get; set; }
        public string modulo { get; set; }
        public string profe { get; set; }
        public int estado { get; set; }
    }
}
