//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkATTdesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasar_listas_grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pasar_listas_grupo()
        {
            this.Pasar_Lista = new HashSet<Pasar_Lista>();
        }
    
        public int id_lista_grupo { get; set; }
        public System.DateTime hora_inicio { get; set; }
        public System.DateTime hora_final { get; set; }
        public string modulo { get; set; }
        public string profe { get; set; }
        public Nullable<int> id_horario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int estado { get; set; }
    
        public virtual Horario Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasar_Lista> Pasar_Lista { get; set; }
    }
}
