//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkATTdesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor()
        {
            this.Clase = new HashSet<Clase>();
            this.Pasar_Lista = new HashSet<Pasar_Lista>();
        }
    
        public int id_profe { get; set; }
        public string dni_profe { get; set; }
        public string nombre_profe { get; set; }
        public string apellido1_profe { get; set; }
        public string apellido2_profe { get; set; }
        public string email_profe { get; set; }
        public string email_centro_profe { get; set; }
        public int tel_profe { get; set; }
        public System.DateTime nacimiento_profe { get; set; }
        public System.DateTime incorp_profe { get; set; }
        public string direccion_profe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clase> Clase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasar_Lista> Pasar_Lista { get; set; }
    }
}
