//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkATTdesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UF()
        {
            this.Pasar_Lista = new HashSet<Pasar_Lista>();
        }
    
        public int id_uf { get; set; }
        public Nullable<int> id_modulo_uf { get; set; }
        public string nombre_uf { get; set; }
        public int horas_totales_uf { get; set; }
        public Nullable<int> horas_cursadas_uf { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasar_Lista> Pasar_Lista { get; set; }
    }
}
